/run_circles:
  ros__parameters:
    color_left:
    - 0
    - 255
    - 0
    color_right:
    - 255
    - 255
    - 255
    start_type_description_service: true
    turtle_velocity: 3.0
    use_sim_time: false

